In [23]:
import pandas as pd
import numpy as np
import os
import math

In [24]:
def apply_pbc(value):
    if abs(value) > 0.5:
        return 1 - abs(value)
    return value


def mic_eucledian_distance(coor1, coor2):
    x_coor1, y_coor1, z_coor1 = coor1
    x_coor2, y_coor2, z_coor2 = coor2
    
    delta_x = x_coor1 - x_coor2
    delta_y = y_coor1 - y_coor2
    delta_z = z_coor1 - z_coor2

    distance = math.sqrt(sum([(apply_pbc(delta_x))**2, (apply_pbc(delta_y))**2, (apply_pbc(delta_z))**2]))
    return distance

In [25]:
file_path_init = "7_2_CONTCAR_init"
file_path = "0_1_CONTCAR"

In [26]:
poscar_line_nr_start = 8        # index from 0
poscar_line_nr_end = 60
amount_Li = 25
n_decimal = 16

In [27]:
with open(file_path_init, 'r') as file_init:
    lines_init = file_init.readlines()
data_init = lines_init[poscar_line_nr_start:poscar_line_nr_start+amount_Li]

df_init = pd.DataFrame([string.strip().split() for string in data_init])
df_float_init = df_init.astype(float)

check_negative_init = df_float_init.lt(0).any().any()

if check_negative_init == True:
    breaksys.exit()    

coordinate_init = [row.to_numpy() for index, row in df_float_init.iterrows()]

In [28]:
with open(file_path, 'r') as file:
    lines = file.readlines()
data = lines[poscar_line_nr_start:poscar_line_nr_start+amount_Li]
data_non_Li = lines[poscar_line_nr_start+amount_Li:poscar_line_nr_end]

df = pd.DataFrame([string.strip().split() for string in data])
df_float = df.astype(float)
df_non_Li = pd.DataFrame([string.strip().split() for string in data_non_Li])
df_float_non_Li = df_non_Li.astype(float)

check_negative = df_float.lt(0).any().any()

if check_negative == True:
    breaksys.exit()

coordinate = [row.to_numpy() for index, row in df_float.iterrows()]

In [29]:
coor_final_reindex = []

for coor_init in coordinate_init:
    distance_prev = float("inf")
    closest24 = None

    for coor in coordinate:
        distance = mic_eucledian_distance(coor_init, coor)

        if distance < distance_prev:
            distance_prev = distance
            closest_coor = coor

    coor_final_reindex.append(closest_coor)

In [31]:
coordinate_init

[array([0.95835192, 0.31685874, 0.33103917]),
 array([0.99430774, 0.70141252, 0.69614921]),
 array([0.02858495, 0.27573254, 0.68386619]),
 array([0.07317737, 0.78755527, 0.07908696]),
 array([0.18178152, 0.19006794, 0.97419491]),
 array([0.34472333, 0.64878575, 0.04763612]),
 array([0.79589717, 0.21510678, 0.02025111]),
 array([0.69483125, 0.67827248, 0.96747641]),
 array([0.19957707, 0.98852095, 0.22489566]),
 array([0.32196063, 0.02614832, 0.73040604]),
 array([0.83198746, 0.96166074, 0.82571183]),
 array([0.82470757, 0.02052615, 0.21474765]),
 array([0.27490918, 0.80022583, 0.48200606]),
 array([0.32964366, 0.21528613, 0.52567716]),
 array([0.72751201, 0.8224285 , 0.52388656]),
 array([0.66606279, 0.17108496, 0.46734986]),
 array([0.213564  , 0.4794397 , 0.70118373]),
 array([0.16863312, 0.54818007, 0.32165261]),
 array([0.71427014, 0.48185846, 0.20961033]),
 array([0.789857  , 0.51568295, 0.66980573]),
 array([0.47820257, 0.32562985, 0.83345355]),
 array([0.4863265 , 0.81195002, 0.

In [32]:
mic_eucledian_distance([0.17105693, 0.96683645, 0.16908302], [0.07317737, 0.78755527, 0.07908696])

0.22320716965077436

In [33]:
mic_eucledian_distance([0.17105693, 0.96683645, 0.16908302], [0.19957707, 0.98852095, 0.22489566])

0.06632244499141447

In [30]:
coordinate

[array([0.95925215, 0.34447747, 0.32042072]),
 array([0.99323301, 0.71739468, 0.71117583]),
 array([0.01875104, 0.29186863, 0.71555644]),
 array([0.02331395, 0.82786646, 0.21236661]),
 array([0.17335943, 0.16544775, 0.96123039]),
 array([0.2153953 , 0.82904815, 0.01366111]),
 array([0.82918122, 0.18927808, 0.04330052]),
 array([0.81283229, 0.77058309, 0.98870562]),
 array([0.30038517, 0.9856086 , 0.31766239]),
 array([0.34389387, 0.02903678, 0.67148767]),
 array([0.81675201, 0.97315171, 0.79915451]),
 array([0.71605072, 0.0186763 , 0.27826118]),
 array([0.18603577, 0.68433832, 0.4604704 ]),
 array([0.22479736, 0.276385  , 0.51125174]),
 array([0.66987611, 0.81378967, 0.55055304]),
 array([0.66806998, 0.1986273 , 0.48238657]),
 array([0.2355876 , 0.48149113, 0.72497127]),
 array([0.30359667, 0.53807559, 0.15980683]),
 array([0.69747867, 0.48361958, 0.17845818]),
 array([0.79835329, 0.51830724, 0.67173529]),
 array([0.46734571, 0.30550342, 0.84300386]),
 array([0.48213951, 0.77287416, 0.

In [34]:
coor_final_reindex

[array([0.95925215, 0.34447747, 0.32042072]),
 array([0.99323301, 0.71739468, 0.71117583]),
 array([0.01875104, 0.29186863, 0.71555644]),
 array([0.02331395, 0.82786646, 0.21236661]),
 array([0.17335943, 0.16544775, 0.96123039]),
 array([0.30359667, 0.53807559, 0.15980683]),
 array([0.82918122, 0.18927808, 0.04330052]),
 array([0.81283229, 0.77058309, 0.98870562]),
 array([0.30038517, 0.9856086 , 0.31766239]),
 array([0.34389387, 0.02903678, 0.67148767]),
 array([0.81675201, 0.97315171, 0.79915451]),
 array([0.71605072, 0.0186763 , 0.27826118]),
 array([0.18603577, 0.68433832, 0.4604704 ]),
 array([0.22479736, 0.276385  , 0.51125174]),
 array([0.66987611, 0.81378967, 0.55055304]),
 array([0.66806998, 0.1986273 , 0.48238657]),
 array([0.2355876 , 0.48149113, 0.72497127]),
 array([0.18603577, 0.68433832, 0.4604704 ]),
 array([0.69747867, 0.48361958, 0.17845818]),
 array([0.79835329, 0.51830724, 0.67173529]),
 array([0.46734571, 0.30550342, 0.84300386]),
 array([0.48213951, 0.77287416, 0.

In [ ]:
# Find duplicate rows and get their indices
unique_rows, indices, counts = np.unique(coor_final_reindex, axis=0, return_index=True, return_counts=True)

# Get the indices of duplicate rows
duplicate_indices = indices[counts > 1]

if len(duplicate_indices) > 0:
    print("Duplicate rows found at indices:", duplicate_indices)
else:
    print("No duplicate rows found.")

In [ ]:
counts

In [ ]:
indices

In [36]:
are_equal = all(np.array_equal(coor_reindex, coor) for coor_reindex, coor in zip(coor_final_reindex, coordinate))

if are_equal:
    print("The arrays are the same.")
else:
    print("The arrays are different.")
    indices_diff = [i for i, (reindex, coord) in enumerate(zip(coor_final_reindex, coordinate)) if not np.array_equal(reindex, coord)]
    print("Indices where the arrays differ:", indices_diff)

The arrays are different.
Indices where the arrays differ: [5, 17]


In [ ]:
df_coordinate = pd.DataFrame(coordinate)
df_concat = pd.concat([df_coordinate, df_float_non_Li], ignore_index=True)

In [ ]:
for i in range(df_concat.shape[0]):
    for j in range(df_concat.shape[1]):
        temp = df_concat[j][i]
        df_concat[j][i] = '{:.{width}f}'.format(float(temp), width=n_decimal)

In [ ]:
row_list = df_concat.to_string(index=False, header=False).split('\n')
row_list_space = ['  '.join(string.split()) for string in row_list] # 2 spaces of distance
row_list_w_beginning = ['  ' + row for row in row_list_space]       # 2 spaces in the beginning
absolute_correct_list = '\n'.join(row_list_w_beginning).splitlines()        

line_append_list = []
for idx_c, line in enumerate(absolute_correct_list):
    line_new_line = str(line) + '\n'
    line_append_list.append(line_new_line)

file_list = lines[:poscar_line_nr_start] + line_append_list

poscar_filename = file_path+"reindexed"
destination_path = poscar_filename

with open(destination_path, "w") as poscar_positive_file:
    for item in file_list:
        poscar_positive_file.writelines(item)